apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: flux-system
spec:
  interval: 30m
  timeout: 9m
  targetNamespace: kserve
  chartRef:
    kind: OCIRepository
    name: kserve-crd-chart
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve
  namespace: flux-system
spec:
  interval: 30m
  timeout: 9m
  dependsOn:
    - name: kserve-crd
    - name: cert-manager
  targetNamespace: kserve
  chartRef:
    kind: OCIRepository
    name: kserve-chart
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kserve:
      controller:
        deploymentMode: Standard
      gateway:
        ingressGateway:
          createGateway: false
