apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../istio
  - ../kgateway-core
  - ../agentgateway-core
  - ../cert-manager
  - ../litellm
  - ../kserve
  - ../tei
  - ../qdrant
  - ../postgres
  - ../redis
  - ../observability
  - ../kagent-core
  - ../kmcp-core
  - ../policies
