apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: context
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql-chart
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      tag: "18.3.0"
    auth:
      username: platform
      password: platform-change-me
      database: platform
    primary:
      persistence:
        size: 20Gi
