apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: context
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql-chart
    namespace: flux-system
  values:
    auth:
      username: platform
      password: platform-change-me
      database: platform
    primary:
      persistence:
        size: 20Gi
