{{- if .Values.remoteMcp.enabled }}
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: {{ .Values.remoteMcp.name }}
  namespace: {{ .Values.namespace }}
spec:
  description: Example echo MCP server managed by kmcp
  protocol: STREAMABLE_HTTP
  url: {{ .Values.remoteMcp.url | quote }}
{{- end }}
