apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-applications
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 12m
  dependsOn:
    - name: platform-runtime
    - name: platform-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/hybrid-remote-dev/apps
