apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: phoenix
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/instance: phoenix
  podMetricsEndpoints:
    - path: /metrics
      targetPort: 9090
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: finnhub-mcp-server
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - kagent
  selector:
    matchLabels:
      app.kubernetes.io/name: finnhub-mcp-backend
      app.kubernetes.io/component: mcp
  podMetricsEndpoints:
    - path: /metrics
      targetPort: 3000
      interval: 30s
      scrapeTimeout: 10s
