apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - referencegrants.yaml
  - backends.yaml
  - httproutes.yaml
  - mcp-backends.yaml
  - mcp-routes.yaml
  - policy.yaml
