"topology":
  "controlPlane":
    "ansible_host": "127.0.0.1"
    "ansible_user": "dmytro"
    "connection": "local"
    "name": "localhost"
    "private_key": ""
  "lmstudio":
    "host": "192.168.1.108"
    "port": 1234
  "metallb":
    "end": "192.168.1.250"
    "start": "192.168.1.240"
  "name": "local"
  "workers": []
