apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  dependsOn:
    - name: kube-prometheus-stack
  targetNamespace: context
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql-chart
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      digest: "sha256:8e4be714e960f58917a7758a82563a72397835a5f448ae46ac6ac8061bc0a662"
    auth:
      username: platform
      database: platform
      existingSecret: platform-postgres-auth
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: password
    primary:
      persistence:
        size: 600Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
