apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-agents
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kagent
  chart:
    spec:
      chart: ./charts/kagent-agents
      sourceRef:
        kind: GitRepository
        name: platform
        namespace: flux-system
      interval: 1m
  values:
    namespace: kagent
    existingSecretName: kagent-agentgateway
    apiKeySecretKey: OPENAI_API_KEY
    modelName: default-gemini
    openaiBaseUrl: http://agentgateway.agentgateway-system.svc.cluster.local:8080/v1
