apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama-runtime
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ai-models
  chart:
    spec:
      chart: ./charts/ollama-runtime
      sourceRef:
        kind: GitRepository
        name: platform
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: ollama-values
      valuesKey: values.yaml
