apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 30m
  timeout: 9m
  targetNamespace: kgateway-system
  chartRef:
    kind: OCIRepository
    name: kgateway-crds-chart
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 30m
  timeout: 9m
  dependsOn:
    - name: kgateway-crds
  targetNamespace: kgateway-system
  chartRef:
    kind: OCIRepository
    name: kgateway-chart
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      image:
        registry: cr.kgateway.dev/kgateway-dev
        repository: kgateway
        tag: v2.1.1
    gateway:
      service:
        type: LoadBalancer
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: kgateway-system-kgateway
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: kgateway-system-kgateway
                namespace: kgateway-system
              spec:
                template:
                  spec:
                    containers:
                      - name: kgateway
                        env:
                          - name: KGW_DEFAULT_IMAGE_TAG
                            value: v2.1.1
