apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  targetNamespace: context
  chart:
    spec:
      chart: qdrant
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    persistence:
      enabled: true
      size: 2.7Gi
