apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bundles/platform-base
  - ../../../bundles/platform-network
  - ../../../bundles/platform-agent-runtime
  - ../../../metallb
