apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/platform-applications
  - generated-echo-mcp-values-configmap.yaml
  - ../../../../overlays/dev
replacements:
  - source:
      kind: ConfigMap
      name: echo-mcp-values
      namespace: flux-system
      fieldPath: data.image
    targets:
      - select:
          kind: MCPServer
          name: echo-mcp
          namespace: kagent
        fieldPaths:
          - spec.deployment.image
