apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../components/platform-core
  - ../../../generated/local
  - ../../../components/platform-runtime-none
  - ../../../overlays/dev
