---
- name: Export kubeconfig to local machine
  hosts: k3s_server
  become: true
  tasks:
    - name: Read kubeconfig
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconf

    - name: Write kubeconfig locally with server host rewritten
      delegate_to: localhost
      become: false
      copy:
        dest: ".kube/generated/{{ inventory_hostname }}.yaml"
        content: "{{ (kubeconf.content | b64decode).replace('127.0.0.1', hostvars[inventory_hostname].ansible_host) }}"
