apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../sources
  - ../metallb
  - ../istio
  - ../kgateway
  - ../agentgateway
  - ../litellm
  - ../kserve
  - ../tei
  - ../qdrant
  - ../postgres
  - ../redis
  - ../observability
  - ../kagent
  - ../kmcp
  - ../policies
