apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - loki.yaml
  - phoenix.yaml
  - otel-collector-traces.yaml
  - tempo.yaml
  - monitors.yaml
