apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: finnhub-mcp-server
  namespace: kagent
spec:
  description: Finnhub MCP server exposed through AgentGateway at /mcp/finnhub-mcp-server for finnhub-agent. It supports natural-language tool discovery, clarification planning, and direct access to all registered Finnhub catalog and endpoint tools.
  protocol: STREAMABLE_HTTP
  timeout: 30s
  sseReadTimeout: 5m0s
  #terminateOnClose: true
  url: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:8080/mcp/finnhub-mcp-server"
