apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/platform-core
  - ../../components/platform-runtime-none
  - ../../secrets/stage
  - ../../overlays/stage
  - ../../generated/minipc
