apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infrastructure/metallb-resources
  - ../../../infrastructure/network/kgateway/resources
  - ../../../apps/ai-gateway/agentgateway/resources
  - ../../../apps/ai-gateway/kagent/resources
patches:
  - target:
      kind: Deployment
      name: litellm
      namespace: ai-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
