apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm-proxy.fullname" . }}-config
  namespace: {{ include "litellm-proxy.namespace" . }}
  labels:
{{ include "litellm-proxy.labels" . | indent 4 }}
data:
  config.yaml: |
{{ required "config must be set" .Values.config | indent 4 }}
