apiVersion: v1
kind: Service
metadata:
  name: {{ include "litellm-proxy.fullname" . }}
  namespace: {{ include "litellm-proxy.namespace" . }}
  labels:
{{ include "litellm-proxy.labels" . | indent 4 }}
spec:
  selector:
{{ include "litellm-proxy.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
