apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infrastructure/metallb-resources
  - ../../../infrastructure/network/kgateway/resources
  - ../../../apps/ai-gateway/agentgateway/resources
  - ../../../apps/ai-gateway/kagent/resources
  - ../../../apps/platform/agentregistry-inventory/resources
  - ../../../apps/platform/kmcp/resources
